# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian"
  config.vm.network :private_network, ip: "192.168.1.55"

  config.vm.provision "ansible" do |ansible| 
    ansible.playbook = "despliegue.yml"
  end

end
