application: ugraerospaceprogram
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: server.application




libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
